version: '3'

services:
  lfbnode0:
    container_name: lfbnode0
    image: "line/lfbnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-lfb.log}
    volumes:
      - ./build:/lfb:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  lfbnode1:
    container_name: lfbnode1
    image: "line/lfbnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-lfb.log}
    volumes:
      - ./build:/lfb:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  lfbnode2:
    container_name: lfbnode2
    image: "line/lfbnode"
    environment:
      - ID=2
      - LOG=${LOG:-lfb.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/lfb:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  lfbnode3:
    container_name: lfbnode3
    image: "line/lfbnode"
    environment:
      - ID=3
      - LOG=${LOG:-lfb.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/lfb:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

