FROM golang:bullseye

# Set working directory for the build
WORKDIR /workdir

# prepare dbbackend before building; this can be cached
COPY Makefile ./
COPY contrib ./contrib/

# Install GO dependencies
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Add source files
COPY . ./

# make a bundle
RUN BUILDDIR=$(realpath $(mktemp -dp .)) && BUILDDIR=$BUILDDIR make build-release-bundle && mv $BUILDDIR/*.tgz bundle.tar.gz
