FROM golang:bullseye

# Set working directory for the build
WORKDIR /workdir

# prepare dbbackend before building; this can be cached
COPY Makefile ./
COPY contrib ./contrib/

# Install GO dependencies
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Add source files
COPY . ./

# make a bundle
RUN CGO_ENABLED=0 make build && cd build && tar -czf bundle.tar.gz *
